from typing import Literal, Dict, Any
from pydantic import BaseModel, Field


class CanonicalDocument(BaseModel):
    """Standard intermediate document representation extracted by format parsers."""

    document_id: str
    document_type: Literal["book", "exam_paper"]
    source_filename: str
    content: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class DocumentChunk(BaseModel):
    """Standard indexing unit generated by type-aware chunkers."""

    chunk_id: str
    document_id: str
    content: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
